name: stride
description: "A new Flutter project."

publish_to: "none" 
environment:
  sdk: ">=3.3.0 <4.0.0"


dependencies:
  animate_do: ^3.3.4
  cached_network_image: ^3.4.1
  carousel_slider: ^4.2.1
  cloud_firestore: ^5.4.4
  connectivity_plus: ^6.0.5
  cupertino_icons: ^1.0.6
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.2
  flutter:
    sdk: flutter
  flutter_image_slider: ^0.0.2
  flutter_native_splash: ^2.4.1
  font_awesome_flutter: ^10.7.0
  get: ^4.6.6
  get_storage: ^2.1.1
  google_sign_in: ^6.2.1
  iconsax: ^0.0.8
  image_picker: ^1.1.2
  intl: ^0.19.0
  logger: ^2.4.0
  lottie: ^3.1.2
  page_transition: ^2.1.0
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter


flutter:
  
  assets:
    - assets/splash.jpg

    #icons
    - assets/icons/menu_32.png
    - assets/icons/bell.png

    #banner
    - assets/banner/banner_adj.jpg
    - assets/banner/banner_2.jpg

    #productslider
    - assets/products/slider/2.jpg
    - assets/products/slider/3.jpg
    - assets/products/slider/4.jpg
    - assets/products/slider/5.jpg
    - assets/products/slider/6.jpg

    #new_arrival
    - assets/products/newarrival/1.jpg
    - assets/products/newarrival/2.jpg
    - assets/products/newarrival/3.jpg
    - assets/products/newarrival/4.jpg
    - assets/products/newarrival/5.jpg

 
  fonts:
    # - family: Schyler
    #   fonts:
    #     - asset: fonts/Schyler-Regular.ttf
    #     - asset: fonts/Schyler-Italic.ttf
    #       style: italic
    - family: Maturascript
      fonts:
        - asset: assets/fonts/maturasc.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  