// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJJG2oaHoYRTqWjpvLpNDumSA9g9fNYrU',
    appId: '1:317266133107:web:749b906998da13dd356a06',
    messagingSenderId: '317266133107',
    projectId: 'stride-79187',
    authDomain: 'stride-79187.firebaseapp.com',
    storageBucket: 'stride-79187.appspot.com',
    measurementId: 'G-RD2XS4M3VX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTJkK4cLP6x-ckVOP34vj6p4E-gpmNVuM',
    appId: '1:317266133107:android:5d4e17187cde659d356a06',
    messagingSenderId: '317266133107',
    projectId: 'stride-79187',
    storageBucket: 'stride-79187.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6Khq-pfvERs1gxcjK2ecyDEAb869c3mw',
    appId: '1:317266133107:ios:1f14fb8758968ebf356a06',
    messagingSenderId: '317266133107',
    projectId: 'stride-79187',
    storageBucket: 'stride-79187.appspot.com',
    iosBundleId: 'com.example.stride',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6Khq-pfvERs1gxcjK2ecyDEAb869c3mw',
    appId: '1:317266133107:ios:1f14fb8758968ebf356a06',
    messagingSenderId: '317266133107',
    projectId: 'stride-79187',
    storageBucket: 'stride-79187.appspot.com',
    iosBundleId: 'com.example.stride',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJJG2oaHoYRTqWjpvLpNDumSA9g9fNYrU',
    appId: '1:317266133107:web:166a43814d5d986c356a06',
    messagingSenderId: '317266133107',
    projectId: 'stride-79187',
    authDomain: 'stride-79187.firebaseapp.com',
    storageBucket: 'stride-79187.appspot.com',
    measurementId: 'G-FR1R137QP0',
  );
}
